# Generated by Django 3.2.5 on 2021-08-22 12:52

import api.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.customuser',),
            managers=[
                ('objects', api.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.customuser',),
            managers=[
                ('objects', api.managers.CustomUserManager()),
            ],
        ),
    ]
